### ISSUE TITLE
[Suggestion] : pythonscriptExecution

### ISSUE THREAD

**Issue by johnmelodyme** [technicaldada/hackerpro#1]
@technicaldada  I suggest to upload these screenshots. 

> Work fine with Ubuntu, Debian and BlackArch linux (tested)

Usage: 

`sudo -i`  To root access.

`cd hackerpro`

`sh intall.sh`
![11](https://user-images.githubusercontent.com/44691957/49919170-a342e600-fee0-11e8-9226-d857902dbb60.png)
![22](https://user-images.githubusercontent.com/44691957/49919191-b655b600-fee0-11e8-98b4-517253fe29d9.png)

`chmod +x hackerpro.py`

` python hackerpro.py`

![33](https://user-images.githubusercontent.com/44691957/49919203-c1104b00-fee0-11e8-825d-e0e5c6cbb1dd.png)

**Comment by technicaldada** [comment]
using `chmod +x` is very basic. thats why is didn't tell that. Thanks for support. Visit [Our Blog](https://www.kalilinux.in) for best hacking tutorials.
