### ISSUE TITLE
Havkerpro not working

### ISSUE THREAD

**Issue by deathride** [technicaldada/hackerpro#3]
ll packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
python is already the newest version (3.7.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ python hackerpro.py
  File "hackerpro.py", line 91
    """
      ^
SyntaxError: invalid syntax
$ python hackerpro.py
  File "hackerpro.py", line 91
    """

**Comment by technicaldada** [comment]
are you using Termux ? Anyway you should try following command:
`python2 hackerpro.py`
